// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1qZPnpFIVjT1k9obpQcBhiPEXFAcdTUM',
    appId: '1:316655320443:web:5256e36484e57562e691de',
    messagingSenderId: '316655320443',
    projectId: 'plant-disease-efef2',
    authDomain: 'plant-disease-efef2.firebaseapp.com',
    storageBucket: 'plant-disease-efef2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzf-Cp7mRUdvnzW9z-qB63nXfwHYqKqJ0',
    appId: '1:316655320443:android:27c30095c5bd757ae691de',
    messagingSenderId: '316655320443',
    projectId: 'plant-disease-efef2',
    storageBucket: 'plant-disease-efef2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgJ25niGkJpvuf6Ma71RGQCmTBc0ZlgNU',
    appId: '1:316655320443:ios:1b15e297dda69a08e691de',
    messagingSenderId: '316655320443',
    projectId: 'plant-disease-efef2',
    storageBucket: 'plant-disease-efef2.firebasestorage.app',
    iosBundleId: 'com.example.plantcarewithai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgJ25niGkJpvuf6Ma71RGQCmTBc0ZlgNU',
    appId: '1:316655320443:ios:1b15e297dda69a08e691de',
    messagingSenderId: '316655320443',
    projectId: 'plant-disease-efef2',
    storageBucket: 'plant-disease-efef2.firebasestorage.app',
    iosBundleId: 'com.example.plantcarewithai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1qZPnpFIVjT1k9obpQcBhiPEXFAcdTUM',
    appId: '1:316655320443:web:e31a9872d75593ece691de',
    messagingSenderId: '316655320443',
    projectId: 'plant-disease-efef2',
    authDomain: 'plant-disease-efef2.firebaseapp.com',
    storageBucket: 'plant-disease-efef2.firebasestorage.app',
  );
}
