// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB441fegqd5M3W92GSiWc6iGodsLyTnLZk',
    appId: '1:1018205901880:web:734a20a637be952d1502cd',
    messagingSenderId: '1018205901880',
    projectId: 'fyp-plant-1ee1e',
    authDomain: 'fyp-plant-1ee1e.firebaseapp.com',
    storageBucket: 'fyp-plant-1ee1e.firebasestorage.app',
    measurementId: 'G-6VFH0TFJZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs6HHG42cw10_XUE_tN-nnY-VRrwKLA3s',
    appId: '1:1018205901880:android:5ea78cb6f820fdaa1502cd',
    messagingSenderId: '1018205901880',
    projectId: 'fyp-plant-1ee1e',
    storageBucket: 'fyp-plant-1ee1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf08fyP-piuXaIiLdyhucvaxDo9qmejZM',
    appId: '1:1018205901880:ios:3b68e8560ff210821502cd',
    messagingSenderId: '1018205901880',
    projectId: 'fyp-plant-1ee1e',
    storageBucket: 'fyp-plant-1ee1e.firebasestorage.app',
    iosBundleId: 'com.example.plantcarewithai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf08fyP-piuXaIiLdyhucvaxDo9qmejZM',
    appId: '1:1018205901880:ios:3b68e8560ff210821502cd',
    messagingSenderId: '1018205901880',
    projectId: 'fyp-plant-1ee1e',
    storageBucket: 'fyp-plant-1ee1e.firebasestorage.app',
    iosBundleId: 'com.example.plantcarewithai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB441fegqd5M3W92GSiWc6iGodsLyTnLZk',
    appId: '1:1018205901880:web:f2f390cb0c95c74a1502cd',
    messagingSenderId: '1018205901880',
    projectId: 'fyp-plant-1ee1e',
    authDomain: 'fyp-plant-1ee1e.firebaseapp.com',
    storageBucket: 'fyp-plant-1ee1e.firebasestorage.app',
    measurementId: 'G-L4CKT1DPC1',
  );
}
